countries:
  - Syria
governantes:
  Damascus & Rif Dimashq: 11
  Homs: 13
  Aleppo: 12
  Hama: 14
  Latakia: 15
  Deir Al Zor: 16
  Daraa: 17
  Idlib: 18
  Al Raqqah: 19
  Al Hasakah: 20
  Tartous: 21
  Al Suwayada: 22
  Al Quneitera: 23
  Outside Syria: 29
statuses:
  - Inactive
  - Active
  - On Hold
  - Under Revision
gender:
  - Male
  - Female
sponsor_type:
  - Individual
  - Organization
orphan_list:
  statuses:
    - Validated
    - Imported
  import:
    first_row: 4
    columns:
      - field: name   
        column: B   
        mandatory: true   
        type: String
      - field: father_name   
        column: C
        mandatory: true   
        type: String
      - field: father_is_martyr
        column: D
        mandatory: true
        type: Boolean
      - field: father_occupation
        column: E
        mandatory: false
        type: String
      - field: father_place_of_death
        column: F
        mandatory: false
        type: String
      - field: father_cause_of_death
        column: G
        mandatory: false
        type: String
      - field: father_date_of_death
        column: H
        mandatory: true
        type: Date
      - field: mother_name
        column: I
        mandatory: true
        type: String
      - field: mother_alive
        column: J
        mandatory: true
        type: Boolean
      - field: date_of_birth
        column: K
        mandatory: true
        type: Date
#      - field: gender   
#        column: L
#        mandatory: true   
#        type: String
      - field: health_status
        column: M
        mandatory: false
        type: String
      - field: schooling_status
        column: N
        mandatory: false
        type: String
      - field: goes_to_school
        column: O
        mandatory: false
        type: String
      - field: guardian_name
        column: Q
        mandatory: true
        type: String
      - field: guardian_relationship
        column: R
        mandatory: true
        type: String
      - field: guardian_id
        column: S
        mandatory: true
        type: Integer
#      - field: original_address_gov
#        column: T
#        mandatory: true
#        type: String
      - field: original_address_city
        column: U
        mandatory: true
        type: String
      - field: original_address_neighborhood
        column: V
        mandatory: false
        type: String
      - field: original_address_street
        column: W
        mandatory: false
        type: String
      - field: original_address_details
        column: X
        mandatory: false
        type: String
#      - field: current_address_gov
#        column: Y
#        mandatory: true
#        type: String
      - field: current_address_city
        column: Z
        mandatory: false
        type: String
      - field: current_address_neighborhood
        column: AA
        mandatory: false
        type: String
      - field: current_address_street
        column: AB
        mandatory: false
        type: String
      - field: current_address_details
        column: AC
        mandatory: false
        type: String
      - field: contact_number
        column: AC
        mandatory: true
        type: String
      - field: alt_contact_number
        column: AD
        mandatory: false
        type: String
      - field: sponsored_by_another_org
        column: AE
        mandatory: true
        type: Boolean
      - field: another_org_sponsorship_details
        column: AF
        mandatory: false
        type: String
      - field: minor_siblings_count
        column: AG
        mandatory: true
        type: Integer
      - field: sponsored_minor_siblings_count
        column: AH
        mandatory: false
        type: Integer
      - field: comments
        column: AL
        mandatory: false
        type: String