countries:
  - Syria
governantes:
  - Damascus
  - Homs
  - Aleppo
statuses:
  - Active
  - Inactive
  - On hold
  - Under Revision
gender:
  - Male
  - Female
sponsor_type:
  - Individual
  - Organization