countries:
  - Syria
governantes:
  Damascus & Rif Dimashq: 11
  Homs: 13
  Aleppo: 12
  Hama: 14
  Latakia: 15
  Deir Al Zor: 16
  Daraa: 17
  Idlib: 18
  Al Raqqah: 19
  Al Hasakah: 20
  Tartous: 21
  Al Suwayada: 22
  Al Quneitera: 23
  Outside Syria: 29
statuses:
  - Inactive
  - Active
  - On Hold
  - Under Revision
orphan_list_statuses:
  - New
  - Valid
  - Invalid
  - Imported
gender:
  - Male
  - Female
sponsor_type:
  - Individual
  - Organization
orphan_list:
  statuses:
    - Pending
    - Imported
  import:
    file_extensions:
      - xls
      - xlsx
    content_types:
      -
      -
    first_row: 4
    first_column: 2
    column_order:
      - name: B
      - father_name: C
      - father_is_martyr: D
      - father_occupation: E
      - father_place_of_death: F
      - father_cause_of_death: G
      - father_date_of_death: H
#      - mother_name:
#      - mother_alive:
#      - date_of_birth:
#      - gender:
#      - health_status:
#      - schooling_status:
#      - goes_to_school:
#      - guardian_name:
#      - guardian_relationship:
#      - guardian_id:
#      - original_address_gov:
#      - original_address_city:
#      - original_address_neighborhood:
#      - original_address_street:
#      - original_address_details:
#      - current_address_gov:
#      - current_address_city:
#      - current_address_neighborhood:
#      - current_address_street:
#      - current_address_details:
#      - contact_number:
#      - alt_contact_number:
#      - sponsored_by_another_org:
#      - another_org_sponsorship_details:
#      - minor_siblings_count:
#      - comments: