countries:
  - Syria
governantes:
  Damascus & Rif Dimashq: 11
  Homs: 13
  Aleppo: 12
  Hama: 14
  Latakia: 15
  Deir Al Zor: 16
  Daraa: 17
  Idlib: 18
  Al Raqqah: 19
  Al Hasakah: 20
  Tartous: 21
  Al Suwayada: 22
  Al Quneitera: 23
  Outside Syria: 29
statuses:
  - Inactive
  - Active
  - On Hold
  - Under Revision
orphan_list_statuses:
  - New
  - Valid
  - Invalid
  - Imported
gender:
  - Male
  - Female
sponsor_type:
  - Individual
  - Organization
orphan_list:
  statuses:
    - Pending
    - Imported
  import:
    file_extensions:
      - xls
      - xlsx
    first_row: 4
    name_col: B
