countries:
  - Syria
governantes:
  Damascus: 11
  Homs: 13
  Aleppo: 12
statuses:
  - Inactive
  - Active
  - On Hold
  - Under Revision
gender:
  - Male
  - Female
sponsor_type:
  - Individual
  - Organization