countries:
  - Syria
governantes:
  Damascus: 11
  Homs: 13
  Aleppo: 12
statuses:
  - Inactive
  - Active
  - On Hold
  - Under Revision
orphan_list_statuses:
  - New
  - Valid
  - Invalid
  - Imported
gender:
  - Male
  - Female
sponsor_type:
  - Individual
  - Organization
orphan_list:
  statuses:
    - Pending
    - Imported
  import:
    file_extensions:
      - xls
      - xlsx
    first_row: 4
    name_col: B
